
package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AppDevService", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://172.16.16.110/GTBTECHAPPDEV/AppDevService.asmx?wsdl")
public class AppDevService
    extends Service
{

    private final static URL APPDEVSERVICE_WSDL_LOCATION;
    private final static WebServiceException APPDEVSERVICE_EXCEPTION;
    private final static QName APPDEVSERVICE_QNAME = new QName("http://tempuri.org/", "AppDevService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://172.16.16.110/GTBTECHAPPDEV/AppDevService.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        APPDEVSERVICE_WSDL_LOCATION = url;
        APPDEVSERVICE_EXCEPTION = e;
    }

    public AppDevService() {
        super(__getWsdlLocation(), APPDEVSERVICE_QNAME);
    }

    public AppDevService(WebServiceFeature... features) {
        super(__getWsdlLocation(), APPDEVSERVICE_QNAME, features);
    }

    public AppDevService(URL wsdlLocation) {
        super(wsdlLocation, APPDEVSERVICE_QNAME);
    }

    public AppDevService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, APPDEVSERVICE_QNAME, features);
    }

    public AppDevService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AppDevService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AppDevServiceSoap
     */
    @WebEndpoint(name = "AppDevServiceSoap")
    public AppDevServiceSoap getAppDevServiceSoap() {
        return super.getPort(new QName("http://tempuri.org/", "AppDevServiceSoap"), AppDevServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AppDevServiceSoap
     */
    @WebEndpoint(name = "AppDevServiceSoap")
    public AppDevServiceSoap getAppDevServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "AppDevServiceSoap"), AppDevServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (APPDEVSERVICE_EXCEPTION!= null) {
            throw APPDEVSERVICE_EXCEPTION;
        }
        return APPDEVSERVICE_WSDL_LOCATION;
    }

}
