
package org.tempuri;

import java.math.BigDecimal;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AppDevServiceSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AppDevServiceSoap {


    /**
     * 
     * @param tokenvalue
     * @param userid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ValidateUserToken", action = "http://tempuri.org/ValidateUserToken")
    @WebResult(name = "ValidateUserTokenResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ValidateUserToken", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ValidateUserToken")
    @ResponseWrapper(localName = "ValidateUserTokenResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ValidateUserTokenResponse")
    public String validateUserToken(
        @WebParam(name = "userid", targetNamespace = "http://tempuri.org/")
        String userid,
        @WebParam(name = "tokenvalue", targetNamespace = "http://tempuri.org/")
        String tokenvalue);

    /**
     * 
     * @param tokenvalue
     * @param purp
     * @param userid
     * @param chann
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ValidateUserToken_New", action = "http://tempuri.org/ValidateUserToken_New")
    @WebResult(name = "ValidateUserToken_NewResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ValidateUserToken_New", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ValidateUserTokenNew")
    @ResponseWrapper(localName = "ValidateUserToken_NewResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ValidateUserTokenNewResponse")
    public String validateUserTokenNew(
        @WebParam(name = "userid", targetNamespace = "http://tempuri.org/")
        String userid,
        @WebParam(name = "tokenvalue", targetNamespace = "http://tempuri.org/")
        String tokenvalue,
        @WebParam(name = "purp", targetNamespace = "http://tempuri.org/")
        String purp,
        @WebParam(name = "chann", targetNamespace = "http://tempuri.org/")
        String chann);

    /**
     * 
     * @param amount
     * @param acctno
     * @param pFreq
     * @param p1StPayDate
     * @param pLastPayDate
     * @param pRemarks
     * @param pAcctToCredit
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "InitiateStandingInstruction2", action = "http://tempuri.org/InitiateStandingInstruction2")
    @WebResult(name = "InitiateStandingInstruction2Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "InitiateStandingInstruction2", targetNamespace = "http://tempuri.org/", className = "org.tempuri.InitiateStandingInstruction2")
    @ResponseWrapper(localName = "InitiateStandingInstruction2Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.InitiateStandingInstruction2Response")
    public String initiateStandingInstruction2(
        @WebParam(name = "acctno", targetNamespace = "http://tempuri.org/")
        String acctno,
        @WebParam(name = "pFreq", targetNamespace = "http://tempuri.org/")
        int pFreq,
        @WebParam(name = "p1stPayDate", targetNamespace = "http://tempuri.org/")
        String p1StPayDate,
        @WebParam(name = "Amount", targetNamespace = "http://tempuri.org/")
        BigDecimal amount,
        @WebParam(name = "pLastPayDate", targetNamespace = "http://tempuri.org/")
        String pLastPayDate,
        @WebParam(name = "pAcctToCredit", targetNamespace = "http://tempuri.org/")
        String pAcctToCredit,
        @WebParam(name = "pRemarks", targetNamespace = "http://tempuri.org/")
        String pRemarks);

    /**
     * 
     * @param benacctno
     * @param type
     * @param userid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ValidateBeneficiaryAccount", action = "http://tempuri.org/ValidateBeneficiaryAccount")
    @WebResult(name = "ValidateBeneficiaryAccountResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ValidateBeneficiaryAccount", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ValidateBeneficiaryAccount")
    @ResponseWrapper(localName = "ValidateBeneficiaryAccountResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ValidateBeneficiaryAccountResponse")
    public String validateBeneficiaryAccount(
        @WebParam(name = "userid", targetNamespace = "http://tempuri.org/")
        String userid,
        @WebParam(name = "benacctno", targetNamespace = "http://tempuri.org/")
        String benacctno,
        @WebParam(name = "type", targetNamespace = "http://tempuri.org/")
        String type);

    /**
     * 
     * @param password
     * @param appid
     * @param userid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ValidateAdminUser", action = "http://tempuri.org/ValidateAdminUser")
    @WebResult(name = "ValidateAdminUserResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ValidateAdminUser", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ValidateAdminUser")
    @ResponseWrapper(localName = "ValidateAdminUserResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ValidateAdminUserResponse")
    public String validateAdminUser(
        @WebParam(name = "userid", targetNamespace = "http://tempuri.org/")
        String userid,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "appid", targetNamespace = "http://tempuri.org/")
        int appid);

    /**
     * 
     * @param password
     * @param code
     * @param appid
     * @param userid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ValidateEncryptedAdminUser", action = "http://tempuri.org/ValidateEncryptedAdminUser")
    @WebResult(name = "ValidateEncryptedAdminUserResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ValidateEncryptedAdminUser", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ValidateEncryptedAdminUser")
    @ResponseWrapper(localName = "ValidateEncryptedAdminUserResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ValidateEncryptedAdminUserResponse")
    public String validateEncryptedAdminUser(
        @WebParam(name = "userid", targetNamespace = "http://tempuri.org/")
        String userid,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "code", targetNamespace = "http://tempuri.org/")
        String code,
        @WebParam(name = "appid", targetNamespace = "http://tempuri.org/")
        int appid);

    /**
     * 
     * @param password
     * @param appid
     * @param userid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ValidateAdminUserOffSite", action = "http://tempuri.org/ValidateAdminUserOffSite")
    @WebResult(name = "ValidateAdminUserOffSiteResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ValidateAdminUserOffSite", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ValidateAdminUserOffSite")
    @ResponseWrapper(localName = "ValidateAdminUserOffSiteResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ValidateAdminUserOffSiteResponse")
    public String validateAdminUserOffSite(
        @WebParam(name = "userid", targetNamespace = "http://tempuri.org/")
        String userid,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "appid", targetNamespace = "http://tempuri.org/")
        int appid);

    /**
     * 
     * @param password
     * @param userid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ValidateUser", action = "http://tempuri.org/ValidateUser")
    @WebResult(name = "ValidateUserResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ValidateUser", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ValidateUser")
    @ResponseWrapper(localName = "ValidateUserResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ValidateUserResponse")
    public String validateUser(
        @WebParam(name = "userid", targetNamespace = "http://tempuri.org/")
        String userid,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password);

    /**
     * 
     * @param ledcode
     * @param cusnum
     * @param curcode
     * @param subacctcode
     * @param bracode
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetAccountBalance", action = "http://tempuri.org/GetAccountBalance")
    @WebResult(name = "GetAccountBalanceResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetAccountBalance", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetAccountBalance")
    @ResponseWrapper(localName = "GetAccountBalanceResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetAccountBalanceResponse")
    public String getAccountBalance(
        @WebParam(name = "bracode", targetNamespace = "http://tempuri.org/")
        String bracode,
        @WebParam(name = "cusnum", targetNamespace = "http://tempuri.org/")
        String cusnum,
        @WebParam(name = "curcode", targetNamespace = "http://tempuri.org/")
        String curcode,
        @WebParam(name = "ledcode", targetNamespace = "http://tempuri.org/")
        String ledcode,
        @WebParam(name = "subacctcode", targetNamespace = "http://tempuri.org/")
        String subacctcode);

    /**
     * 
     * @param branchCode
     * @param ledgerCode
     * @param customerNumber
     * @param currencyCode
     * @param subAccount
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetAccountStatus", action = "http://tempuri.org/GetAccountStatus")
    @WebResult(name = "GetAccountStatusResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetAccountStatus", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetAccountStatus")
    @ResponseWrapper(localName = "GetAccountStatusResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetAccountStatusResponse")
    public String getAccountStatus(
        @WebParam(name = "branchCode", targetNamespace = "http://tempuri.org/")
        String branchCode,
        @WebParam(name = "customerNumber", targetNamespace = "http://tempuri.org/")
        String customerNumber,
        @WebParam(name = "currencyCode", targetNamespace = "http://tempuri.org/")
        int currencyCode,
        @WebParam(name = "ledgerCode", targetNamespace = "http://tempuri.org/")
        String ledgerCode,
        @WebParam(name = "subAccount", targetNamespace = "http://tempuri.org/")
        int subAccount);

    /**
     * 
     * @param account
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetCustomerByAccount", action = "http://tempuri.org/GetCustomerByAccount")
    @WebResult(name = "GetCustomerByAccountResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetCustomerByAccount", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCustomerByAccount")
    @ResponseWrapper(localName = "GetCustomerByAccountResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCustomerByAccountResponse")
    public String getCustomerByAccount(
        @WebParam(name = "account", targetNamespace = "http://tempuri.org/")
        String account);

    /**
     * 
     * @param reference
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetCRNoteDetails", action = "http://tempuri.org/GetCRNoteDetails")
    @WebResult(name = "GetCRNoteDetailsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetCRNoteDetails", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCRNoteDetails")
    @ResponseWrapper(localName = "GetCRNoteDetailsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCRNoteDetailsResponse")
    public String getCRNoteDetails(
        @WebParam(name = "reference", targetNamespace = "http://tempuri.org/")
        String reference);

    /**
     * 
     * @param reference
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetDRNoteDetails", action = "http://tempuri.org/GetDRNoteDetails")
    @WebResult(name = "GetDRNoteDetailsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetDRNoteDetails", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetDRNoteDetails")
    @ResponseWrapper(localName = "GetDRNoteDetailsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetDRNoteDetailsResponse")
    public String getDRNoteDetails(
        @WebParam(name = "reference", targetNamespace = "http://tempuri.org/")
        String reference);

    /**
     * 
     * @param cusnum
     * @param bracode
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetCustomerName", action = "http://tempuri.org/GetCustomerName")
    @WebResult(name = "GetCustomerNameResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetCustomerName", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCustomerName")
    @ResponseWrapper(localName = "GetCustomerNameResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCustomerNameResponse")
    public String getCustomerName(
        @WebParam(name = "bracode", targetNamespace = "http://tempuri.org/")
        String bracode,
        @WebParam(name = "cusnum", targetNamespace = "http://tempuri.org/")
        String cusnum);

    /**
     * 
     * @param currencyCode
     * @param columnName
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetExchangeRate", action = "http://tempuri.org/GetExchangeRate")
    @WebResult(name = "GetExchangeRateResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetExchangeRate", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetExchangeRate")
    @ResponseWrapper(localName = "GetExchangeRateResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetExchangeRateResponse")
    public String getExchangeRate(
        @WebParam(name = "currencyCode", targetNamespace = "http://tempuri.org/")
        String currencyCode,
        @WebParam(name = "columnName", targetNamespace = "http://tempuri.org/")
        String columnName);

    /**
     * 
     * @param ledcode
     * @param cusnum
     * @param curcode
     * @param subacctcode
     * @param bracode
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetLastTransactionDetails", action = "http://tempuri.org/GetLastTransactionDetails")
    @WebResult(name = "GetLastTransactionDetailsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetLastTransactionDetails", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetLastTransactionDetails")
    @ResponseWrapper(localName = "GetLastTransactionDetailsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetLastTransactionDetailsResponse")
    public String getLastTransactionDetails(
        @WebParam(name = "bracode", targetNamespace = "http://tempuri.org/")
        int bracode,
        @WebParam(name = "cusnum", targetNamespace = "http://tempuri.org/")
        int cusnum,
        @WebParam(name = "curcode", targetNamespace = "http://tempuri.org/")
        int curcode,
        @WebParam(name = "ledcode", targetNamespace = "http://tempuri.org/")
        int ledcode,
        @WebParam(name = "subacctcode", targetNamespace = "http://tempuri.org/")
        int subacctcode);

    /**
     * 
     * @param ledcode
     * @param cusnum
     * @param curcode
     * @param custemail
     * @param subacctcode
     * @param bracode
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetLastAccountStatement", action = "http://tempuri.org/GetLastAccountStatement")
    @WebResult(name = "GetLastAccountStatementResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetLastAccountStatement", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetLastAccountStatement")
    @ResponseWrapper(localName = "GetLastAccountStatementResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetLastAccountStatementResponse")
    public String getLastAccountStatement(
        @WebParam(name = "bracode", targetNamespace = "http://tempuri.org/")
        int bracode,
        @WebParam(name = "cusnum", targetNamespace = "http://tempuri.org/")
        int cusnum,
        @WebParam(name = "curcode", targetNamespace = "http://tempuri.org/")
        int curcode,
        @WebParam(name = "ledcode", targetNamespace = "http://tempuri.org/")
        int ledcode,
        @WebParam(name = "subacctcode", targetNamespace = "http://tempuri.org/")
        int subacctcode,
        @WebParam(name = "custemail", targetNamespace = "http://tempuri.org/")
        String custemail);

    /**
     * 
     * @param ledcode
     * @param cusnum
     * @param curcode
     * @param subacctcode
     * @param bracode
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "RequestChequeBook", action = "http://tempuri.org/RequestChequeBook")
    @WebResult(name = "RequestChequeBookResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RequestChequeBook", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RequestChequeBook")
    @ResponseWrapper(localName = "RequestChequeBookResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RequestChequeBookResponse")
    public String requestChequeBook(
        @WebParam(name = "bracode", targetNamespace = "http://tempuri.org/")
        int bracode,
        @WebParam(name = "cusnum", targetNamespace = "http://tempuri.org/")
        int cusnum,
        @WebParam(name = "curcode", targetNamespace = "http://tempuri.org/")
        int curcode,
        @WebParam(name = "ledcode", targetNamespace = "http://tempuri.org/")
        int ledcode,
        @WebParam(name = "subacctcode", targetNamespace = "http://tempuri.org/")
        int subacctcode);

    /**
     * 
     * @param ledcode
     * @param amount
     * @param cusnum
     * @param stop
     * @param curcode
     * @param start
     * @param subacctcode
     * @param bracode
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "StopCheque", action = "http://tempuri.org/StopCheque")
    @WebResult(name = "StopChequeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "StopCheque", targetNamespace = "http://tempuri.org/", className = "org.tempuri.StopCheque")
    @ResponseWrapper(localName = "StopChequeResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.StopChequeResponse")
    public String stopCheque(
        @WebParam(name = "bracode", targetNamespace = "http://tempuri.org/")
        int bracode,
        @WebParam(name = "cusnum", targetNamespace = "http://tempuri.org/")
        int cusnum,
        @WebParam(name = "curcode", targetNamespace = "http://tempuri.org/")
        int curcode,
        @WebParam(name = "ledcode", targetNamespace = "http://tempuri.org/")
        int ledcode,
        @WebParam(name = "subacctcode", targetNamespace = "http://tempuri.org/")
        int subacctcode,
        @WebParam(name = "start", targetNamespace = "http://tempuri.org/")
        int start,
        @WebParam(name = "stop", targetNamespace = "http://tempuri.org/")
        int stop,
        @WebParam(name = "amount", targetNamespace = "http://tempuri.org/")
        String amount);

    /**
     * 
     * @param ledcode
     * @param cusnum
     * @param curcode
     * @param subacctcode
     * @param bracode
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ConfirmCheque", action = "http://tempuri.org/ConfirmCheque")
    @WebResult(name = "ConfirmChequeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ConfirmCheque", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConfirmCheque")
    @ResponseWrapper(localName = "ConfirmChequeResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConfirmChequeResponse")
    public String confirmCheque(
        @WebParam(name = "bracode", targetNamespace = "http://tempuri.org/")
        int bracode,
        @WebParam(name = "cusnum", targetNamespace = "http://tempuri.org/")
        int cusnum,
        @WebParam(name = "curcode", targetNamespace = "http://tempuri.org/")
        int curcode,
        @WebParam(name = "ledcode", targetNamespace = "http://tempuri.org/")
        int ledcode,
        @WebParam(name = "subacctcode", targetNamespace = "http://tempuri.org/")
        int subacctcode);

    /**
     * 
     * @param amount
     * @param acctFro
     * @param channel
     * @param acctTo
     * @param type
     * @param remarks
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "TransferFund", action = "http://tempuri.org/TransferFund")
    @WebResult(name = "TransferFundResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "TransferFund", targetNamespace = "http://tempuri.org/", className = "org.tempuri.TransferFund")
    @ResponseWrapper(localName = "TransferFundResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.TransferFundResponse")
    public String transferFund(
        @WebParam(name = "Acct_fro", targetNamespace = "http://tempuri.org/")
        String acctFro,
        @WebParam(name = "Acct_to", targetNamespace = "http://tempuri.org/")
        String acctTo,
        @WebParam(name = "Amount", targetNamespace = "http://tempuri.org/")
        double amount,
        @WebParam(name = "type", targetNamespace = "http://tempuri.org/")
        String type,
        @WebParam(name = "channel", targetNamespace = "http://tempuri.org/")
        String channel,
        @WebParam(name = "Remarks", targetNamespace = "http://tempuri.org/")
        String remarks);

    /**
     * 
     * @param amount
     * @param acctFro
     * @param acctTo
     * @param remarks
     * @param explCode
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Transfer", action = "http://tempuri.org/Transfer")
    @WebResult(name = "TransferResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Transfer", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Transfer")
    @ResponseWrapper(localName = "TransferResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.TransferResponse")
    public String transfer(
        @WebParam(name = "Acct_fro", targetNamespace = "http://tempuri.org/")
        String acctFro,
        @WebParam(name = "Acct_to", targetNamespace = "http://tempuri.org/")
        String acctTo,
        @WebParam(name = "Amount", targetNamespace = "http://tempuri.org/")
        double amount,
        @WebParam(name = "expl_code", targetNamespace = "http://tempuri.org/")
        int explCode,
        @WebParam(name = "Remarks", targetNamespace = "http://tempuri.org/")
        String remarks);

    /**
     * 
     * @param amount
     * @param acctFro
     * @param rate
     * @param crossrate
     * @param channel
     * @param acctTo
     * @param type
     * @param remarks
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "TransferFund_Cross", action = "http://tempuri.org/TransferFund_Cross")
    @WebResult(name = "TransferFund_CrossResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "TransferFund_Cross", targetNamespace = "http://tempuri.org/", className = "org.tempuri.TransferFundCross")
    @ResponseWrapper(localName = "TransferFund_CrossResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.TransferFundCrossResponse")
    public String transferFundCross(
        @WebParam(name = "Acct_fro", targetNamespace = "http://tempuri.org/")
        String acctFro,
        @WebParam(name = "Acct_to", targetNamespace = "http://tempuri.org/")
        String acctTo,
        @WebParam(name = "Amount", targetNamespace = "http://tempuri.org/")
        double amount,
        @WebParam(name = "rate", targetNamespace = "http://tempuri.org/")
        double rate,
        @WebParam(name = "crossrate", targetNamespace = "http://tempuri.org/")
        double crossrate,
        @WebParam(name = "type", targetNamespace = "http://tempuri.org/")
        String type,
        @WebParam(name = "channel", targetNamespace = "http://tempuri.org/")
        String channel,
        @WebParam(name = "Remarks", targetNamespace = "http://tempuri.org/")
        String remarks);

    /**
     * 
     * @param docnum
     * @param identifier
     * @param amount
     * @param acctFro
     * @param channel
     * @param acctTo
     * @param days
     * @param type
     * @param remarks
     * @param bankcode
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "TransferCheques", action = "http://tempuri.org/TransferCheques")
    @WebResult(name = "TransferChequesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "TransferCheques", targetNamespace = "http://tempuri.org/", className = "org.tempuri.TransferCheques")
    @ResponseWrapper(localName = "TransferChequesResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.TransferChequesResponse")
    public String transferCheques(
        @WebParam(name = "Acct_fro", targetNamespace = "http://tempuri.org/")
        String acctFro,
        @WebParam(name = "Acct_to", targetNamespace = "http://tempuri.org/")
        String acctTo,
        @WebParam(name = "Amount", targetNamespace = "http://tempuri.org/")
        double amount,
        @WebParam(name = "type", targetNamespace = "http://tempuri.org/")
        String type,
        @WebParam(name = "channel", targetNamespace = "http://tempuri.org/")
        String channel,
        @WebParam(name = "Remarks", targetNamespace = "http://tempuri.org/")
        String remarks,
        @WebParam(name = "docnum", targetNamespace = "http://tempuri.org/")
        String docnum,
        @WebParam(name = "identifier", targetNamespace = "http://tempuri.org/")
        short identifier,
        @WebParam(name = "bankcode", targetNamespace = "http://tempuri.org/")
        short bankcode,
        @WebParam(name = "days", targetNamespace = "http://tempuri.org/")
        short days);

    /**
     * 
     * @param userid
     * @param phoneno
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SendSMS", action = "http://tempuri.org/SendSMS")
    @WebResult(name = "SendSMSResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SendSMS", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendSMS")
    @ResponseWrapper(localName = "SendSMSResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendSMSResponse")
    public String sendSMS(
        @WebParam(name = "userid", targetNamespace = "http://tempuri.org/")
        String userid,
        @WebParam(name = "phoneno", targetNamespace = "http://tempuri.org/")
        String phoneno);

    /**
     * 
     * @param attachment
     * @param subject
     * @param emailto
     * @param emailfrom
     * @param mailmessage
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SendEmail", action = "http://tempuri.org/SendEmail")
    @WebResult(name = "SendEmailResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SendEmail", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendEmail")
    @ResponseWrapper(localName = "SendEmailResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendEmailResponse")
    public String sendEmail(
        @WebParam(name = "subject", targetNamespace = "http://tempuri.org/")
        String subject,
        @WebParam(name = "mailmessage", targetNamespace = "http://tempuri.org/")
        String mailmessage,
        @WebParam(name = "emailfrom", targetNamespace = "http://tempuri.org/")
        String emailfrom,
        @WebParam(name = "emailto", targetNamespace = "http://tempuri.org/")
        String emailto,
        @WebParam(name = "attachment", targetNamespace = "http://tempuri.org/")
        String attachment);

    /**
     * 
     * @param userid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ResetUserPasscode", action = "http://tempuri.org/ResetUserPasscode")
    @WebResult(name = "ResetUserPasscodeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ResetUserPasscode", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ResetUserPasscode")
    @ResponseWrapper(localName = "ResetUserPasscodeResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ResetUserPasscodeResponse")
    public String resetUserPasscode(
        @WebParam(name = "userid", targetNamespace = "http://tempuri.org/")
        String userid);

    /**
     * 
     * @param pass
     * @param userid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ChangeUserPasscode", action = "http://tempuri.org/ChangeUserPasscode")
    @WebResult(name = "ChangeUserPasscodeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ChangeUserPasscode", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ChangeUserPasscode")
    @ResponseWrapper(localName = "ChangeUserPasscodeResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ChangeUserPasscodeResponse")
    public String changeUserPasscode(
        @WebParam(name = "userid", targetNamespace = "http://tempuri.org/")
        String userid,
        @WebParam(name = "pass", targetNamespace = "http://tempuri.org/")
        String pass);

    /**
     * 
     * @param pswd
     * @param userid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ChangeAdminUserPasscode", action = "http://tempuri.org/ChangeAdminUserPasscode")
    @WebResult(name = "ChangeAdminUserPasscodeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ChangeAdminUserPasscode", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ChangeAdminUserPasscode")
    @ResponseWrapper(localName = "ChangeAdminUserPasscodeResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ChangeAdminUserPasscodeResponse")
    public String changeAdminUserPasscode(
        @WebParam(name = "userid", targetNamespace = "http://tempuri.org/")
        String userid,
        @WebParam(name = "pswd", targetNamespace = "http://tempuri.org/")
        String pswd);

    /**
     * 
     * @param roleid
     * @param appid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetApplicationRoleUsers", action = "http://tempuri.org/GetApplicationRoleUsers")
    @WebResult(name = "GetApplicationRoleUsersResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetApplicationRoleUsers", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetApplicationRoleUsers")
    @ResponseWrapper(localName = "GetApplicationRoleUsersResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetApplicationRoleUsersResponse")
    public String getApplicationRoleUsers(
        @WebParam(name = "roleid", targetNamespace = "http://tempuri.org/")
        int roleid,
        @WebParam(name = "appid", targetNamespace = "http://tempuri.org/")
        int appid);

    /**
     * 
     * @param uid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetAdminUserName", action = "http://tempuri.org/GetAdminUserName")
    @WebResult(name = "GetAdminUserNameResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetAdminUserName", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetAdminUserName")
    @ResponseWrapper(localName = "GetAdminUserNameResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetAdminUserNameResponse")
    public String getAdminUserName(
        @WebParam(name = "uid", targetNamespace = "http://tempuri.org/")
        String uid);

    /**
     * 
     * @param userid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetCustomerDetails", action = "http://tempuri.org/GetCustomerDetails")
    @WebResult(name = "GetCustomerDetailsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetCustomerDetails", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCustomerDetails")
    @ResponseWrapper(localName = "GetCustomerDetailsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCustomerDetailsResponse")
    public String getCustomerDetails(
        @WebParam(name = "userid", targetNamespace = "http://tempuri.org/")
        String userid);

    /**
     * 
     * @param acctno
     * @param userid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ValidateAccount", action = "http://tempuri.org/ValidateAccount")
    @WebResult(name = "ValidateAccountResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ValidateAccount", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ValidateAccount")
    @ResponseWrapper(localName = "ValidateAccountResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ValidateAccountResponse")
    public String validateAccount(
        @WebParam(name = "userid", targetNamespace = "http://tempuri.org/")
        String userid,
        @WebParam(name = "acctno", targetNamespace = "http://tempuri.org/")
        String acctno);

    /**
     * 
     * @param uid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CheckUserFlag", action = "http://tempuri.org/CheckUserFlag")
    @WebResult(name = "CheckUserFlagResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CheckUserFlag", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CheckUserFlag")
    @ResponseWrapper(localName = "CheckUserFlagResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CheckUserFlagResponse")
    public String checkUserFlag(
        @WebParam(name = "uid", targetNamespace = "http://tempuri.org/")
        String uid);

    /**
     * 
     * @param uid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ResetUserFlag", action = "http://tempuri.org/ResetUserFlag")
    @WebResult(name = "ResetUserFlagResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ResetUserFlag", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ResetUserFlag")
    @ResponseWrapper(localName = "ResetUserFlagResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ResetUserFlagResponse")
    public String resetUserFlag(
        @WebParam(name = "uid", targetNamespace = "http://tempuri.org/")
        String uid);

    /**
     * 
     * @param datavalue
     * @param key
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "EncryptData", action = "http://tempuri.org/EncryptData")
    @WebResult(name = "EncryptDataResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "EncryptData", targetNamespace = "http://tempuri.org/", className = "org.tempuri.EncryptData")
    @ResponseWrapper(localName = "EncryptDataResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.EncryptDataResponse")
    public String encryptData(
        @WebParam(name = "datavalue", targetNamespace = "http://tempuri.org/")
        String datavalue,
        @WebParam(name = "key", targetNamespace = "http://tempuri.org/")
        String key);

    /**
     * 
     * @param datavalue
     * @param key
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "DecryptData", action = "http://tempuri.org/DecryptData")
    @WebResult(name = "DecryptDataResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "DecryptData", targetNamespace = "http://tempuri.org/", className = "org.tempuri.DecryptData")
    @ResponseWrapper(localName = "DecryptDataResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.DecryptDataResponse")
    public String decryptData(
        @WebParam(name = "datavalue", targetNamespace = "http://tempuri.org/")
        String datavalue,
        @WebParam(name = "key", targetNamespace = "http://tempuri.org/")
        String key);

    /**
     * 
     * @param ivrinfo
     * @param chanid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "TransferCTI", action = "http://tempuri.org/TransferCTI")
    @WebResult(name = "TransferCTIResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "TransferCTI", targetNamespace = "http://tempuri.org/", className = "org.tempuri.TransferCTI")
    @ResponseWrapper(localName = "TransferCTIResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.TransferCTIResponse")
    public String transferCTI(
        @WebParam(name = "IVRINFO", targetNamespace = "http://tempuri.org/")
        String ivrinfo,
        @WebParam(name = "CHANID", targetNamespace = "http://tempuri.org/")
        String chanid);

    /**
     * 
     * @param chanid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "StartCTI", action = "http://tempuri.org/StartCTI")
    @WebResult(name = "StartCTIResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "StartCTI", targetNamespace = "http://tempuri.org/", className = "org.tempuri.StartCTI")
    @ResponseWrapper(localName = "StartCTIResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.StartCTIResponse")
    public String startCTI(
        @WebParam(name = "CHANID", targetNamespace = "http://tempuri.org/")
        String chanid);

    /**
     * 
     * @param appID
     * @param action
     * @param userid
     * @param staffid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "LogAdminUserAction", action = "http://tempuri.org/LogAdminUserAction")
    @WebResult(name = "LogAdminUserActionResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "LogAdminUserAction", targetNamespace = "http://tempuri.org/", className = "org.tempuri.LogAdminUserAction")
    @ResponseWrapper(localName = "LogAdminUserActionResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.LogAdminUserActionResponse")
    public String logAdminUserAction(
        @WebParam(name = "AppID", targetNamespace = "http://tempuri.org/")
        int appID,
        @WebParam(name = "userid", targetNamespace = "http://tempuri.org/")
        String userid,
        @WebParam(name = "staffid", targetNamespace = "http://tempuri.org/")
        long staffid,
        @WebParam(name = "Action", targetNamespace = "http://tempuri.org/")
        String action);

    /**
     * 
     * @param branchCode
     * @param password
     * @param roleid
     * @param basisid
     * @param emailaddress
     * @param userID
     * @param staffid
     * @param username
     * @param status
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "AddNewAdminUser", action = "http://tempuri.org/AddNewAdminUser")
    @WebResult(name = "AddNewAdminUserResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "AddNewAdminUser", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AddNewAdminUser")
    @ResponseWrapper(localName = "AddNewAdminUserResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AddNewAdminUserResponse")
    public String addNewAdminUser(
        @WebParam(name = "UserID", targetNamespace = "http://tempuri.org/")
        String userID,
        @WebParam(name = "BASISID", targetNamespace = "http://tempuri.org/")
        int basisid,
        @WebParam(name = "Username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "staffid", targetNamespace = "http://tempuri.org/")
        String staffid,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "branch_code", targetNamespace = "http://tempuri.org/")
        int branchCode,
        @WebParam(name = "emailaddress", targetNamespace = "http://tempuri.org/")
        String emailaddress,
        @WebParam(name = "roleid", targetNamespace = "http://tempuri.org/")
        String roleid,
        @WebParam(name = "status", targetNamespace = "http://tempuri.org/")
        String status);

    /**
     * 
     * @param branchCode
     * @param roleid
     * @param basisid
     * @param emailaddress
     * @param userID
     * @param staffid
     * @param username
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "UpdateAdminUser", action = "http://tempuri.org/UpdateAdminUser")
    @WebResult(name = "UpdateAdminUserResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "UpdateAdminUser", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UpdateAdminUser")
    @ResponseWrapper(localName = "UpdateAdminUserResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UpdateAdminUserResponse")
    public String updateAdminUser(
        @WebParam(name = "UserID", targetNamespace = "http://tempuri.org/")
        String userID,
        @WebParam(name = "BASISID", targetNamespace = "http://tempuri.org/")
        int basisid,
        @WebParam(name = "Username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "staffid", targetNamespace = "http://tempuri.org/")
        String staffid,
        @WebParam(name = "branch_code", targetNamespace = "http://tempuri.org/")
        int branchCode,
        @WebParam(name = "emailaddress", targetNamespace = "http://tempuri.org/")
        String emailaddress,
        @WebParam(name = "roleid", targetNamespace = "http://tempuri.org/")
        String roleid);

    /**
     * 
     * @param userID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetAdminUserDetails", action = "http://tempuri.org/GetAdminUserDetails")
    @WebResult(name = "GetAdminUserDetailsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetAdminUserDetails", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetAdminUserDetails")
    @ResponseWrapper(localName = "GetAdminUserDetailsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetAdminUserDetailsResponse")
    public String getAdminUserDetails(
        @WebParam(name = "UserID", targetNamespace = "http://tempuri.org/")
        String userID);

    /**
     * 
     * @param str
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SearchAdminUser", action = "http://tempuri.org/SearchAdminUser")
    @WebResult(name = "SearchAdminUserResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SearchAdminUser", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SearchAdminUser")
    @ResponseWrapper(localName = "SearchAdminUserResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SearchAdminUserResponse")
    public String searchAdminUser(
        @WebParam(name = "str", targetNamespace = "http://tempuri.org/")
        String str);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetAllRoles", action = "http://tempuri.org/GetAllRoles")
    @WebResult(name = "GetAllRolesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetAllRoles", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetAllRoles")
    @ResponseWrapper(localName = "GetAllRolesResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetAllRolesResponse")
    public String getAllRoles();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetAllAdminUsers", action = "http://tempuri.org/GetAllAdminUsers")
    @WebResult(name = "GetAllAdminUsersResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetAllAdminUsers", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetAllAdminUsers")
    @ResponseWrapper(localName = "GetAllAdminUsersResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetAllAdminUsersResponse")
    public String getAllAdminUsers();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetAllBranches", action = "http://tempuri.org/GetAllBranches")
    @WebResult(name = "GetAllBranchesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetAllBranches", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetAllBranches")
    @ResponseWrapper(localName = "GetAllBranchesResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetAllBranchesResponse")
    public String getAllBranches();

    /**
     * 
     * @param userid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ActivateAdminUser", action = "http://tempuri.org/ActivateAdminUser")
    @WebResult(name = "ActivateAdminUserResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ActivateAdminUser", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ActivateAdminUser")
    @ResponseWrapper(localName = "ActivateAdminUserResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ActivateAdminUserResponse")
    public String activateAdminUser(
        @WebParam(name = "userid", targetNamespace = "http://tempuri.org/")
        String userid);

    /**
     * 
     * @param userid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "DeactivateAdminUser", action = "http://tempuri.org/DeactivateAdminUser")
    @WebResult(name = "DeactivateAdminUserResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "DeactivateAdminUser", targetNamespace = "http://tempuri.org/", className = "org.tempuri.DeactivateAdminUser")
    @ResponseWrapper(localName = "DeactivateAdminUserResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.DeactivateAdminUserResponse")
    public String deactivateAdminUser(
        @WebParam(name = "userid", targetNamespace = "http://tempuri.org/")
        String userid);

    /**
     * 
     * @param appid
     * @param userid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetTellerTillAcct", action = "http://tempuri.org/GetTellerTillAcct")
    @WebResult(name = "GetTellerTillAcctResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetTellerTillAcct", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetTellerTillAcct")
    @ResponseWrapper(localName = "GetTellerTillAcctResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetTellerTillAcctResponse")
    public String getTellerTillAcct(
        @WebParam(name = "userid", targetNamespace = "http://tempuri.org/")
        String userid,
        @WebParam(name = "appid", targetNamespace = "http://tempuri.org/")
        int appid);

    /**
     * 
     * @param branchCode
     * @param appid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetZoneAcct", action = "http://tempuri.org/GetZoneAcct")
    @WebResult(name = "GetZoneAcctResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetZoneAcct", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetZoneAcct")
    @ResponseWrapper(localName = "GetZoneAcctResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetZoneAcctResponse")
    public String getZoneAcct(
        @WebParam(name = "branch_code", targetNamespace = "http://tempuri.org/")
        int branchCode,
        @WebParam(name = "appid", targetNamespace = "http://tempuri.org/")
        int appid);

    /**
     * 
     * @param appid
     * @param userid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetBranchAcct", action = "http://tempuri.org/GetBranchAcct")
    @WebResult(name = "GetBranchAcctResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetBranchAcct", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetBranchAcct")
    @ResponseWrapper(localName = "GetBranchAcctResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetBranchAcctResponse")
    public String getBranchAcct(
        @WebParam(name = "userid", targetNamespace = "http://tempuri.org/")
        String userid,
        @WebParam(name = "appid", targetNamespace = "http://tempuri.org/")
        int appid);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetAllBasisRoles", action = "http://tempuri.org/GetAllBasisRoles")
    @WebResult(name = "GetAllBasisRolesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetAllBasisRoles", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetAllBasisRoles")
    @ResponseWrapper(localName = "GetAllBasisRolesResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetAllBasisRolesResponse")
    public String getAllBasisRoles();

    /**
     * 
     * @param acctno
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ValidateBASISAccount", action = "http://tempuri.org/ValidateBASISAccount")
    @WebResult(name = "ValidateBASISAccountResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ValidateBASISAccount", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ValidateBASISAccount")
    @ResponseWrapper(localName = "ValidateBASISAccountResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ValidateBASISAccountResponse")
    public String validateBASISAccount(
        @WebParam(name = "acctno", targetNamespace = "http://tempuri.org/")
        String acctno);

    /**
     * 
     * @param branchCode
     * @param customerNo
     * @return
     *     returns org.tempuri.CustDetRetVal
     */
    @WebMethod(operationName = "GetBasisCustomerDetails", action = "http://tempuri.org/GetBasisCustomerDetails")
    @WebResult(name = "GetBasisCustomerDetailsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetBasisCustomerDetails", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetBasisCustomerDetails")
    @ResponseWrapper(localName = "GetBasisCustomerDetailsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetBasisCustomerDetailsResponse")
    public CustDetRetVal getBasisCustomerDetails(
        @WebParam(name = "branch_code", targetNamespace = "http://tempuri.org/")
        int branchCode,
        @WebParam(name = "Customer_no", targetNamespace = "http://tempuri.org/")
        int customerNo);

    /**
     * 
     * @param appid
     * @param userid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetBasisTellerTillAcct", action = "http://tempuri.org/GetBasisTellerTillAcct")
    @WebResult(name = "GetBasisTellerTillAcctResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetBasisTellerTillAcct", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetBasisTellerTillAcct")
    @ResponseWrapper(localName = "GetBasisTellerTillAcctResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetBasisTellerTillAcctResponse")
    public String getBasisTellerTillAcct(
        @WebParam(name = "userid", targetNamespace = "http://tempuri.org/")
        String userid,
        @WebParam(name = "appid", targetNamespace = "http://tempuri.org/")
        int appid);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetAllBasisUsers", action = "http://tempuri.org/GetAllBasisUsers")
    @WebResult(name = "GetAllBasisUsersResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetAllBasisUsers", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetAllBasisUsers")
    @ResponseWrapper(localName = "GetAllBasisUsersResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetAllBasisUsersResponse")
    public String getAllBasisUsers();

    /**
     * 
     * @param roleDesc
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "AddEoneRole", action = "http://tempuri.org/AddEoneRole")
    @WebResult(name = "AddEoneRoleResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "AddEoneRole", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AddEoneRole")
    @ResponseWrapper(localName = "AddEoneRoleResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AddEoneRoleResponse")
    public String addEoneRole(
        @WebParam(name = "role_desc", targetNamespace = "http://tempuri.org/")
        String roleDesc);

    /**
     * 
     * @param roleDesc
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "AddBasisRole", action = "http://tempuri.org/AddBasisRole")
    @WebResult(name = "AddBasisRoleResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "AddBasisRole", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AddBasisRole")
    @ResponseWrapper(localName = "AddBasisRoleResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AddBasisRoleResponse")
    public String addBasisRole(
        @WebParam(name = "role_desc", targetNamespace = "http://tempuri.org/")
        String roleDesc);

    /**
     * 
     * @param branchCode
     * @param password
     * @param updateFlag
     * @param roleid
     * @param basisid
     * @param username
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "AddNewTeller", action = "http://tempuri.org/AddNewTeller")
    @WebResult(name = "AddNewTellerResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "AddNewTeller", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AddNewTeller")
    @ResponseWrapper(localName = "AddNewTellerResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AddNewTellerResponse")
    public String addNewTeller(
        @WebParam(name = "BASISID", targetNamespace = "http://tempuri.org/")
        int basisid,
        @WebParam(name = "Username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "branch_code", targetNamespace = "http://tempuri.org/")
        int branchCode,
        @WebParam(name = "roleid", targetNamespace = "http://tempuri.org/")
        String roleid,
        @WebParam(name = "UpdateFlag", targetNamespace = "http://tempuri.org/")
        String updateFlag);

    /**
     * 
     * @param str
     * @param branchCode
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SearchBASISUser", action = "http://tempuri.org/SearchBASISUser")
    @WebResult(name = "SearchBASISUserResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SearchBASISUser", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SearchBASISUser")
    @ResponseWrapper(localName = "SearchBASISUserResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SearchBASISUserResponse")
    public String searchBASISUser(
        @WebParam(name = "str", targetNamespace = "http://tempuri.org/")
        String str,
        @WebParam(name = "branch_code", targetNamespace = "http://tempuri.org/")
        String branchCode);

    /**
     * 
     * @param analDate
     * @param acctno
     * @param transferAmt
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "AnalyzeFx", action = "http://tempuri.org/AnalyzeFx")
    @WebResult(name = "AnalyzeFxResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "AnalyzeFx", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AnalyzeFx")
    @ResponseWrapper(localName = "AnalyzeFxResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AnalyzeFxResponse")
    public String analyzeFx(
        @WebParam(name = "acctno", targetNamespace = "http://tempuri.org/")
        String acctno,
        @WebParam(name = "transfer_amt", targetNamespace = "http://tempuri.org/")
        BigDecimal transferAmt,
        @WebParam(name = "anal_date", targetNamespace = "http://tempuri.org/")
        XMLGregorianCalendar analDate);

}
